- name: variable to print
  hosts: web
  vars: # Varialbe declaration in Play level
    NAME: Ravi
  tasks:
  - name: print the varaiable
    ansible.builtin.debug:
      msg: "This is {{NAME}}"
  - name: print the varaiable1
    vars:
      NAME: Amireddy
    ansible.builtin.debug:
      msg: "This is {{NAME}}"
  - name: print the varaiable 2
    ansible.builtin.debug:
      msg: "This is {{NAME}} from"