- name: varaible preference 
  hosts: web
  vars:
    NAME: "FROM VARS"
  vars_prompt:
  - name: NAME
    prompt: "Please enter the name"
    private: false
  vars_files:
  - vars.yml
  tasks: # list of tasks
  - name: Play 01 task1
    vars:
      NAME: "Ravikumar Aireddy"
    ansible.builtin.debug:
      msg: "task1 from  Play 01"