- name: varaible preference 
  hosts: web
  vars:
    NAME: "FROM VARS"
  vars_files:
  - vars.yml
  vars_prompt:
  - name: NAME
    prompt: "Please enter the name"
    private: false
  tasks: # list of tasks
  - name: Play 01 task1
    vars:
      NAME: "Ravikumar Aireddy"
    ansible.builtin.debug:
     msg: "This is {{NAME}}"

# - name: variables preference
#   hosts: web
#   vars:
#     NAME: "DevOps with AWS from PLAY level"
#   vars_files:
#   - vars.yml
#   vars_prompt:
#   - name: NAME
#     prompt: Please enter the name
#     private: false # not confidential
#   tasks:
#   - name: print the information
#     vars:
#       NAME: "DevOps with AWS from TASK level"
#     ansible.builtin.debug:
#       msg: "Hi, This is {{NAME}}"

#1. command line/args
#2. Task level
#3. Files
#4. prompt
#5. Play
#6. inventory
#7. Roles