- name: check the numer is less than 10
  hosts: local
  vars_prompt:
    - name: number
      prompt: Please enter the number
      private: false
  tasks:
  - name: print this less than 10
    ansible.builtin.debug:
      msg: "Given number {{ number }} is less than 10"
    when: number | int < 10
    
  - name: print this greater than 10
    ansible.builtin.debug:
      msg: "Given number {{ number }} is greater than or equal to 10"
    when: number | int >= 10

