- name: create user
  hosts: web'
  become: yes
  tasks:
  - name: create user exists or not
    ansible.builtin.command: id expense
      resiger: USER 
  - name: print the USER Info
    ansible.builtinf.debug:
      msg: "User info : {{ USER }}"