- name: demo on filters/fuctions
  hosts: local
  connection: local
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"
  - name: convert to UPPERCASE
    vars:
      greeting: "Hello saanvi"
    ansible.builtin.debug:
      msg: "{{ greeting | upper}}"
  - name: convert to lowercase
    vars:
      greeting: "Hello saanvi"
    ansible.builtin.debug:
      msg: "{{ greeting | lower}}"
  - name: convert to unique
    vars:
      numbers: [1,5,63,23,6,1,2,5]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"
  - name: min & max
    vars:
      numbers: [1,5,63,23,6,1,2,5]
    ansible.builtin.debug:
      msg: "Min : {{ numbers | min }}, Max: {{ numbers | max }}"
  - name: convert map to list
    vars:
      course:
        name: "DevOps"
        trainer: "Siva"
        duration: 120
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"
  - name: convert list to map
    vars:
      - courses:
        - name: "DevOps"
          trainer: "Siva"
        - name: "Java"
          trainer: "Ravi"
    ansible.builtin.debug:
      msg: "{{ courses | items2dict }}"