- name: create ec2 and r53 record
  hosts: local
  connection: local
  vars:
    subnet_id: 
    sg_id:
    ami_id:
    instances:
    - mysql
    - backend
    - fronend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_imstance:
      name: {{ item }}
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instance
